version: 2.1
orbs: 
  browser-tools: circleci/browser-tools@1.4.0
jobs:
  build:
    docker:
      - image: cimg/node:current-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run: npm install
      - run: npm test