version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:current-browsers
    steps:
      - checkout
      - run: npm install
      - run:
        name: Run Test
        command: npm test
